spring:
  #配置数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 
    #配置tomcat数据池
    tomcat:
      default-auto-commit: true
      max-wait: 500
      max-active: 100
      max-idle: 30

  #配置redis,哨兵
 redis:
   password: 
   sentinel:
     master: MASTER_REDIS
     nodes: 127.0.0.1:8001,127.0.0.1:8002,127.0.0.1:8003
   timeout: 3000
   pool:
     max-idle: 10
     min-idle: 5
     max-wait: 3000